pretrained_model_path: "model/dreamlikePhotoreal20_ema"
vae: 
  single_file: True 
  model_path: "vae/vae-ft-mse-840000-ema-pruned.safetensors"

motion_module_path: "animatediff-motion-adapter-v1-5-2"

controlnet:
  - model_path: "controlnet/control_v11p_sd15_openpose"
    image_path: "controlnet-image/openpose.gif"
    conditioning_scale: 0.5
  - model_path: "controlnet/control_v11p_sd15_lineart"
    image_path: "controlnet-image/lineart_coarse.gif"
    conditioning_scale: 0.5

prompt: "a girl, walking, best quality, extremely detailed"
negative_prompt: "longbody, lowres, bad anatomy, bad hands, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality"

seed: 222
steps: 5
guidance_scale: 7.5

ip_adapter:
  enable: True
  folder: "IP-Adapter"
  subfolder: "models"
  weight_name: "ip-adapter-plus_sd15.safetensors"
  image_path: "girl.png"
  scale: 0.6

lcm_lora:
  enable: True
  model_path: "lora/lcm-lora-sdv1-5"
  weight: 1.0
